### ISSUE TITLE
请问如何安装需要的软件? 

### ISSUE THREAD

**Issue by neoedmund** [fritx/nw-chat#2]
我只安装了node.js. 有没有安装使用的流程说明? 谢谢.

`>npm run lint

> nw-chat@0.0.0 lint E:\neoe\oss\nw-chat
> eslint src test

'eslint' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw-chat@0.0.0 lint: `eslint src test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nw-chat@0.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\neoe\AppData\Roaming\npm-cache\_logs\xxxxxxx-debug.log`

**Comment by fritx** [comment]
@neoedmund 你好，因为一般我们默认都是熟悉nodejs的开发者，所以省掉了很多指南信息。

这个项目时间比较久远了，找个时间我也试一试，一般来说完整的步骤是：

```plain
cd nw-chat
npm install

npm run dev  # 在一个tab里开着，会自动编译web

npm start  # 在另一个tab执行，运行app
```
